### ISSUE TITLE
Song screen doesn't scroll down to follow playback cursor

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#277]
When the playback cursor goes off screen by playing the next row not visible on the Song screen, the screen does not scroll itself to follow the cursor so that the currently playing row is displayed on screen. 

This is disorientating behaviour as there is no other way on the UI to see the currently playing row.

An added wrinkle here is that different rows can be playing in different tracks (columns). For that case I think it would be acceptable to try to show at least the left most playing columns currently playing row.

**Comment by democloid** [comment]
I don't quite agree on this one. The screens are mainly editing screens, and playback cursor is added as a visual aid, but don't think it should take over scrolling. What happens when you're looking at something and the screen needs to scroll and you're editing cursor is in the first row? does it disappear? move over to another row? Don't think either of those are desirable

The fact that the playing cursor could end up in two different screens and you'd have to make an arbitrary decision on which one to follow makes this even worse IMO.

**Comment by maks** [comment]
@democloid good point about that! I was influenced on this by how Milkytracker does scroll with playback but its an option there to turn off and playing a bit more with it, I think you're right and it won't work well on the pT UI.
