### ISSUE TITLE
Generate random project names

### ISSUE THREAD

**Issue by maks** [xiphonics/picoTracker#46]
Entering names 1 char at a time with the arrow keys is tedious and results in my naming projects like "A", "B" "C1", etc.

It would be nice to have functionality to generate random names but ones still short enough to quickly edit if required.

Bonus: this could be done with minimal impact on runtime ram usage.

**Comment by maks** [comment]
I've had a quick go at the generator class in the WIP PR linked to this issue, but still need to wire it up to the project file browser, but will hold off on doing that pending results of ongoing discussion about the file browser UI in #31

**Comment by democloid** [comment]
@maks I was thinking about something unrelated I got me in the direction of this issue. I guess the problem we are trying to solve with this is getting started quickly with a project and create some name for it, right? (not so much finding a name for a project itself)

In that sense, I was thinking that maybe the first screen when we turn on picoTracker should be a new (unnamed) empty project, where we can go and load a new project if we want to (and the load screen should be a pop up rather than an independent screen like it is today). Thoughts?

**Comment by maks** [comment]
I think these might be related but separate issues.
With generating random names, that's not so much about getting started quickly as even if we created new unnamed projects, I'd still need to spend time typing in a name once I wanted to do the first save. So this is more around providing a quick "autofill" if you like for a project name when I dont want to spend any time and effort coming up with and then entering a name for a project.
But I do also agree with having a better power-on flow. Both the PE Tracker and M8 open the last used project on power up (I think the Digitone does too?), so I think that pretty common and useful behaviour that would be nice to have in the pico too, especially if we could detect that the prev projects samples are already in flash so could skip that step as that can be bit time consuming and not necessary. If you are happy with that suggestion, I can add a separate issue for that too?

**Comment by maks** [comment]
done as of #219
