### ISSUE TITLE
Can't access samplelib after previewing samples

### ISSUE THREAD

**Issue by Djeroek** [xiphonics/picoTracker#93]
Hello,

I'm on build 1.1r_2 and have had the following issue;

When accessing sounds, previewing them to make a choise for which one to use in an instrument, i've already had multiple instances where a sound froze during preview. Resulting in not being able to access the samples anymore; "Can't access the samplelib" every time I try to enter "sample: (null) through double clicking. Only way to have this working again afaik is rebooting the system.

I know about the file type limitations of the unit. Will try to see if I can replicate the issue and share the particular sound causing issues.

**Comment by maks** [comment]
Thanks for filing this issue. If you are able to replicate with a sample or several samples that you are able to share here that would really help in debugging whats happening.

**Comment by maks** [comment]
To have a bit of a baseline I've attached here the "tardline" track project so that people can try loading and playing it to see if it works. If it does, then that gives us a starting point for comparing samples that don't work to try to track down what could be causing a problem.

[lgptTardline__M-_-n.zip](https://github.com/democloid/picoTracker/files/14049276/lgptTardline__M-_-n.zip)

**Comment by maks** [comment]
Going to close this one out as sample browser was completely redone for v2.0. Please re-open if this is still reproducable with latest v2.0 beta release.
